### ISSUE TITLE
Error with Sprockets 4

### ISSUE THREAD

**Issue by frodrigo** [railsware/smt_rails#19]
```
~/.gem/gems/smt_rails-0.2.9/lib/smt_rails/engine.rb:9:in `block (2 levels) in <class:Engine>': undefined method `register_engine' for #<Sprockets::Environment:0x00000004f20130> (NoMethodError)
Did you mean?  register_pipeline
	from /home/fred/.gem/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:179:in `block in build_environment'
	from /home/fred/.gem/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:178:in `each'
	from /home/fred/.gem/gems/sprockets-rails-3.2.0/lib/sprockets/railtie.rb:178:in `build_environment'
```

**Comment by le0pard** [comment]
Hello @frodrigo . This gem never was tested with Sprockets 3 or 4, so I am sure, it will not work.
